<a href="https://colab.research.google.com/github/plaban1981/simpletransformers/blob/master/Simple_Transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


https://medium.com/swlh/simple-transformers-multi-class-text-classification-with-bert-roberta-xlnet-xlm-and-8b585000ce3a

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
train = pd.read_csv('/content/drive/My Drive/Zindi/Tech4MentalHealth/Train.csv')
test = pd.read_csv('/content/drive/My Drive/Zindi/Tech4MentalHealth/Test.csv')

In [3]:
train.head()

ID                                               text       label
0  SUAVK39Z            I feel that it was better I dieAm happy  Depression
1  9JDAGUV3                       Why do I get hallucinations?       Drugs
2  419WR1LQ  I am stresseed due to lack of financial suppor...  Depression
3  6UY7DX6Q                             Why is life important?     Suicide
4  FYC0FTFB  How could I be helped to go through the depres...  Depression

In [4]:
import torch

In [7]:
pip install transformers

     |████████████████████████████████| 757kB 2.8MB/s 
     |████████████████████████████████| 3.0MB 16.2MB/s 
     |████████████████████████████████| 1.1MB 30.3MB/s 
     |████████████████████████████████| 890kB 37.0MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893260 sha256=51e0068d63a64ded43198584eb24463415687b105b0a9ea8656f01fd6139e955
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [8]:
pip install simpletransformers

     |████████████████████████████████| 204kB 2.8MB/s 
     |████████████████████████████████| 71kB 5.0MB/s 
     |████████████████████████████████| 317kB 8.5MB/s 
  Created wheel for seqeval: filename=seqeval-0.0.12-cp36-none-any.whl size=7424 sha256=a164d81fab82053f9ba65ca8ff82de0ab468ed7a26dc01dbe6fedcba08edb768
  Stored in directory: /root/.cache/pip/wheels/4f/32/0a/df3b340a82583566975377d65e724895b3fad101a3fb729f68
Successfully built seqeval
  Found existing installation: tqdm 4.41.1
    Uninstalling tqdm-4.41.1:
      Successfully uninstalled tqdm-4.41.1


In [5]:
from simpletransformers.classification import ClassificationModel

In [6]:
 from sklearn.preprocessing import LabelEncoder
 lb = LabelEncoder()
 label_enc = lb.fit_transform(train['label'])

In [7]:
lb.classes_

array(['Alcohol', 'Depression', 'Drugs', 'Suicide'], dtype=object)

In [12]:
data = train[['text','label']].copy()

In [15]:
data['label'] = label_enc

In [16]:
data.head()

text  label
0            I feel that it was better I dieAm happy      1
1                       Why do I get hallucinations?      2
2  I am stresseed due to lack of financial suppor...      1
3                             Why is life important?      3
4  How could I be helped to go through the depres...      1

In [17]:
data.label.unique()

array([1, 2, 3, 0])

In [52]:
# Create a ClassificationModel
model = ClassificationModel('roberta', 'roberta-base', num_labels=4)
#model = ClassificationModel('bert', 'bert-base-uncased', num_labels=4)
#model = ClassificationModel('xlnet', 'xlnet-base-cased', num_labels=4)

Some weights of the model checkpoint at roberta-base were not used when initializing RobertaForSequenceClassification: ['lm_head.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.weight', 'classifier.dense.bias', 'classifier.out_proj.weight', 'classifier.out

## Install apex in Colab

In [20]:
!git clone https://github.com/NVIDIA/apex

Cloning into 'apex'...
remote: Enumerating objects: 74, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 7329 (delta 37), reused 39 (delta 19), pack-reused 7255
Receiving objects: 100% (7329/7329), 13.88 MiB | 7.58 MiB/s, done.
Resolving deltas: 100% (4938/4938), done.


In [28]:
%%writefile setup.sh

git clone https://github.com/NVIDIA/apex
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./apex

Writing setup.sh


In [29]:
!sh setup.sh

fatal: destination path 'apex' already exists and is not an empty directory.
/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py:283: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Created temporary directory: /tmp/pip-ephem-wheel-cache-vnnwofaz
Created temporary directory: /tmp/pip-req-tracker-zpa7_c4c
Created requirements tracker '/tmp/pip-req-tracker-zpa7_c4c'
Created temporary directory: /tmp/pip-install-4flz0s_r
Processing ./apex
  Created temporary directory: /tmp/pip-req-build-qupqi80s
  Added file:///content/apex to build tracker '/tmp/pip-req-tracker-zpa7_c4c'
    Running setup.py (path:/tmp/pip-req-build-qupqi80s/setup.py) egg_info for package from file:///content/apex
    Running command python setup.py egg_info


    torch.__version__  = 1.5.1+cu101


    running egg_info
    creating /tmp/pip-req-build-qupqi80s/pip-egg-info/apex.egg-info

In [69]:
# Train the model
model.train_model(data,args={'learning_rate':1e-5, 'num_train_epochs': 5, 'reprocess_input_data': True, 'overwrite_output_dir': True})

/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/classification_model.py:277: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  "Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels."



Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic


/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:114: UserWarning: Seems like `optimizer.step()` has been overridden after learning rate scheduler initialization. Please, make sure to call `optimizer.step()` before `lr_scheduler.step()`. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)


Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 32768.0
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 16384.0


/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:231: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  warnings.warn("To get the last learning rate computed by the scheduler, "


/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:200: UserWarning: Please also save or load the state of the optimzer when saving or loading the scheduler.
  warnings.warn(SAVE_STATE_WARNING, UserWarning)


Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 8192.0



In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test= train_test_split(data,test_size=0.20,random_state=42)

In [89]:
from sklearn.metrics import f1_score, accuracy_score,log_loss


def f1_multiclass(labels, preds):
    return f1_score(labels, preds, average='micro')
def logloss_multiclass(labels, preds):
    return log_loss(labels, preds,labels=4)
    
result, model_outputs, wrong_predictions = model.eval_model(X_test, acc=accuracy_score)


/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/classification_model.py:747: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  "Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels."


In [82]:
result, model_outputs, wrong_predictions = model.eval_model(X_test)

/usr/local/lib/python3.6/dist-packages/simpletransformers/classification/classification_model.py:747: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  "Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels."


# Result ROBERTA

In [90]:
result

{'acc': 0.9838709677419355,
 'eval_loss': 0.04193767160177231,
 'mcc': 0.9754911688827148}

* result: The evaluation result in the form of a dict. By default, **only the Matthews correlation coefficient (MCC) is calculated for multiclass classification**.

* model_outputs: A list of model outputs for each item in the evaluation dataset. This is useful if you need probabilities for each class rather than a single prediction. Indeed, the prediction is calculated by applying a softmax function over the outputs.

* wrong_predictions: A list of InputFeature of each incorrect prediction. The text may be obtained from the InputFeature.text_a attribute. (The InputFeature class can be found in the utils.py file in the repo)

# Make Predictions on test/ new text data

In [72]:
test_data = test.drop('ID',axis=1)

In [73]:
test_data.head()

text
0          How to overcome bad feelings and emotions
1                     I feel like giving up in life 
2  I was so depressed feel like got no strength t...
3  I feel so low especially since I had no one to...
4       can i be successful when I am a drug addict?

In [74]:

predictions, raw_outputs = model.predict(test_data['text'])

In [75]:
predictions

array([1, 1, 1, 1, 2, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1,
       0, 1, 3, 1, 1, 1, 1, 1, 1, 3, 2, 1, 1, 2, 1, 3, 1, 2, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 3, 1, 0, 0, 0, 1, 3, 3, 1,
       1, 1, 3, 1, 1, 3, 1, 2, 1, 1, 0, 3, 1, 0, 1, 1, 0, 0, 1, 1, 2, 0,
       1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 3, 2, 3, 1, 1, 1, 1, 0, 2,
       1, 1, 1, 2, 3, 0, 3, 0, 1, 3, 1, 1, 1, 3, 0, 1, 3, 0, 1, 1, 0, 0,
       1, 3, 3, 1, 1, 2, 2, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 3, 1,
       2, 1, 1, 0, 1, 1, 0, 3, 0, 0, 3, 3, 1, 1, 1, 1, 1, 0, 3, 0, 0, 2,
       3, 1, 0, 1, 1, 3, 1, 0, 0, 3, 1, 0, 2, 2, 2, 1, 1, 3, 1, 1, 0, 2,
       1, 1, 0, 0, 1, 3, 1, 0, 1, 0, 1, 3, 1, 0, 1, 2, 1, 1, 0, 0, 1, 1,
       1, 3, 3, 1, 3, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 3, 1, 1, 1, 1,
       3, 1, 1, 1, 0, 0, 3, 0, 1, 1, 1, 1, 0, 1, 1, 2, 1, 2, 1, 3, 1, 1,
       3, 0, 0, 2, 1, 3, 1, 2, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 3, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 3, 1, 2, 1, 1,

In [76]:
raw_outputs

array([[-1.2441406 ,  2.6503906 , -2.9277344 ,  1.9287109 ],
       [-2.0273438 ,  5.8554688 , -1.9208984 , -1.3525391 ],
       [-1.9277344 ,  5.8242188 , -1.9277344 , -1.4091797 ],
       ...,
       [-0.32080078, -0.2902832 , -2.1191406 ,  2.5585938 ],
       [-1.1630859 , -1.9208984 ,  4.6054688 , -1.1357422 ],
       [ 2.2460938 , -0.80029297, -1.7216797 ,  0.48608398]],
      dtype=float32)

In [77]:
results = pd.DataFrame(raw_outputs,columns=lb.classes_)

In [78]:
results.head()

Alcohol  Depression     Drugs   Suicide
0 -1.244141    2.650391 -2.927734  1.928711
1 -2.027344    5.855469 -1.920898 -1.352539
2 -1.927734    5.824219 -1.927734 -1.409180
3 -1.933594    5.808594 -1.937500 -1.410156
4  0.363525   -2.828125  3.484375 -0.881348

In [79]:
df_sub = pd.concat([test,results],axis=1)

In [80]:
df_sub.head()

ID  ...   Suicide
0  02V56KMO  ...  1.928711
1  03BMGTOK  ... -1.352539
2  03LZVFM6  ... -1.409180
3  0EPULUM5  ... -1.410156
4  0GM4C5GD  ... -0.881348

[5 rows x 6 columns]

In [81]:
df_sub[['ID','Depression','Alcohol','Suicide','Drugs']].to_csv('transformers_new.csv',index=False)

## Result XLNET

In [51]:
result

{'acc': 0.6693548387096774,
 'eval_loss': 0.7879994418472052,
 'f1': 0.6693548387096774,
 'mcc': 0.48513626572830737}

## Result Bert

In [45]:
result

{'acc': 0.6854838709677419,
 'eval_loss': 0.8045708071440458,
 'f1': 0.6854838709677419,
 'mcc': 0.5162326475386168}

In [47]:
model_outputs

array([[ 7.97851562e-01, -7.59277344e-01, -5.46386719e-01,
        -1.07226562e+00],
       [-1.93969727e-01,  7.04101562e-01, -5.24414062e-01,
        -8.34960938e-01],
       [ 9.78393555e-02, -6.10351562e-01, -4.10400391e-01,
        -1.11425781e+00],
       [-1.43798828e-01,  5.89370728e-04, -6.91894531e-01,
        -9.82910156e-01],
       [-5.63476562e-01,  1.47656250e+00, -1.07910156e+00,
        -8.09570312e-01],
       [-6.38427734e-02,  5.88073730e-02, -7.32421875e-01,
        -1.00097656e+00],
       [ 8.87207031e-01, -9.74121094e-01, -4.52880859e-01,
        -8.17871094e-01],
       [-1.36962891e-01, -5.05371094e-01, -4.31152344e-01,
        -9.96093750e-01],
       [-8.23730469e-01,  1.96289062e+00, -1.02539062e+00,
        -4.40185547e-01],
       [-8.11035156e-01,  2.03515625e+00, -9.45312500e-01,
        -3.81835938e-01],
       [-4.54101562e-01,  1.29199219e+00, -1.11035156e+00,
        -7.42675781e-01],
       [ 7.79296875e-01, -1.01953125e+00, -3.40087891e-01,
      